### ISSUE TITLE
Feature Request: set custom rating name for each smiley

### ISSUE THREAD

**Issue by rama-2402** [unaisulhadi/EmojiRatingBar#1]
Can you please add the feature to add custom names for each smiley rating to display. Thanks

**Comment by unaisulhadi** [comment]
Will try to add. Thanks for suggestion

**Comment by rama-2402** [comment]
@unaisulhadi  Any update or ETA on when this feature will be added?

**Comment by unaisulhadi** [comment]
@rama-2402 Thank you for your patience, I've added feature requested by you, you  can use that from latest release. 

Sample code is attached below.

```kotlin
        emojiRatingBar.setAwfulEmojiTitle("Awful!")
        emojiRatingBar.setBadEmojiTitle("Bad!")
        emojiRatingBar.setOkayEmojiTitle("Okay!")
        emojiRatingBar.setGoodEmojiTitle("Good!")
        emojiRatingBar.setGreatEmojiTitle("Great!")
```

**Comment by rama-2402** [comment]
> @rama-2402 Thank you for your patience, I've added feature requested by you, you can use that from latest release.
> 
> Sample code is attached below.
> 
> ```kotlin
>         emojiRatingBar.setAwfulEmojiTitle("Awful!")
>         emojiRatingBar.setBadEmojiTitle("Bad!")
>         emojiRatingBar.setOkayEmojiTitle("Okay!")
>         emojiRatingBar.setGoodEmojiTitle("Good!")
>         emojiRatingBar.setGreatEmojiTitle("Great!")
> ```

Thank you for simple and perfect library. :)
